### ISSUE TITLE
Unexplained Crash

### ISSUE THREAD

**Issue by Rabcor** [xylosper/bomi#127] opened 2014-10-15 20:46 UTC
I've encountered an odd crash with a file, I cannot provide the file but you should be able to find it somewhere if you seek **The Legend of Korra - The Complete Season 2 [HDTV - 720p]** which was the torrent name where I got it from.

Filename: 
**The.Legend.of.Korra.S02E01-E02.Rebel.Spirit_Southern.Lights.720p.HDTV.x264-W4F.mkv** it is the first episode, and the first crash occurs at exactly **08:47**

I've tested this file with Mpv and with K-Lite Codecs(Windows) neither had this crash problem.

**Comment by xylosper** [comment] 2015-01-09 12:23
Can you test again with latest git source?

**Comment by Rabcor** [comment] 2015-01-27 17:57
I would love to but I honestly have no idea how to compile from git, I always used the cmplayer-git aur package, but someone had it removed.

**Comment by xylosper** [comment] 2015-01-27 19:15
Install bomi-git instead.

**Comment by Rabcor** [comment] 2015-01-27 20:10
Ah there we go, thanks :+1: why'd you change the name? Does it mean anything special?

I tried it again, it still crashes the same way. (I checked with gdb also)

**Comment by xylosper** [comment] 2015-01-27 20:15
Because CMPlayer is not a unique name. There are two minor programs already at least.

Still same log? 

Also, maybe there could be some curruption in your file. Can you share it through for instance, Google Drive or DropBox?

**Comment by Rabcor** [comment] 2015-01-27 20:39
Yeah same log. I don't think the file is corrupted (it plays fine in other media players) and even if it was corrupted, it definitely shouldn't crash the whole player. Especially since other media players can play it just fine is all the more reason to investigate further.

As for the file, it's a big file (900mb) I remember there was another episode or two that crashed as well, but I can't remember which ones (nor the timing) I'll see if I can find them. (That would be 350mb or so) (Oh yeah, since it wasn't unique to one file that sort of gives us away that this was not file specific, i.e. not a corrupt file.)

I think you already downloaded the correct files a while back when you looked for them though. Let me just finish updating my system first, I've been off linux for almost a month now which is why you haven't been hearing from me (that's about to change though). But it will be good to confirm whether you can reproduce this on your end or not. Are you using an Nvidia GPU on proprietary drivers as well?

**Comment by xylosper** [comment] 2015-01-27 20:43
> Yeah same log. I don't think the file is corrupted (it plays fine in other media players) and even if it was corrupted, it definitely shouldn't crash the whole player. Especially since other media players can play it just fine is all the more reason to investigate further.

That's why asked a sample.

> since it wasn't unique to one file that sort of gives us away that this was not file specific, i.e. not a corrupt file

Some released series can be totally broken by stupid encoder or wrong usage.

> But it will be good to confirm whether you can reproduce this on your end or not. 

No I couldn't. This is way I asked a sample, too.

> Are you using an Nvidia GPU on proprietary drivers as well?

Yes.

**Comment by Rabcor** [comment] 2015-01-27 20:47
Yes like I said, after I finish updating I will look for a smaller sample to give you. I need to restart to be able to playback files in the player since I updated my graphics drivers. I will upload the sample to mediafire if that is ok?

**Comment by xylosper** [comment] 2015-01-27 20:49
I think that would be fine.

**Comment by Rabcor** [comment] 2015-01-27 21:31
Seems you were right, it was a corrupt file, and running it in gdb it did properly detect it this time.

    [mpv/mkv] Corrupt file detected. Trying to resync starting from position 20978034...
    [mpv/mkv] Cluster found at 21069630.
    qml: true true
    [Thread 0x7fffb741b700 (LWP 2505) exited]

However as I did say before, since other players (including mpv) can manage to struggle through it even if it has faulty encoding, Bomi should too.

Anyhow, I found a smaller file, it crashes at 17:42. It was an oddly quick upload, but I uploaded it here.

http://www.mediafire.com/download/bfvq11b1oz2mvzb/The.Legend.of.Korra.S02E03.Civil.Wars.Part.1.720p.HDTV.x264-W4F.mkv

**Comment by xylosper** [comment] 2015-01-27 22:19
I can't download your link. I got a 'Permission Denied.'.

**Comment by Rabcor** [comment] 2015-01-27 23:47
Here I uploaded it properly http://www.mediafire.com/download/20my7gp962kvc26/e3.rar

The password is xylosper

**Comment by xylosper** [comment] 2015-02-08 13:31
Finally, I succeed to reproduce your problem and I think it's fixed now. Please try it with git package.

**Comment by Rabcor** [comment] 2015-02-20 15:42
Yup, this time it didn't crash for me either (sorry for late reply btw) it just made some strange buzzing sound for a second, that however is something I think everyone can live with :+1:

**Comment by xylosper** [comment] 2015-02-28 03:11
Thank for feedback.

**Closed by xylosper** 2015-02-28 03:11 UTC
