### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ForumLiker** [xylosper/bomi#267] opened 2015-03-16 12:54 UTC
-Where settings are stored locally?
-How to add a program to the list of applications by default?

**Comment by breed808** [comment] 2015-03-16 13:04
Settings are stored in ~/.config/xylosper and ~/.config/xylosper/bomi for Linux systems.

**Comment by ForumLiker** [comment] 2015-03-16 16:50
Hi. Sorry,forgot to specify system))) Ubuntu 14.10
-hotkeys in what file?

**Comment by xylosper** [comment] 2015-03-18 09:27
> -How to add a program to the list of applications by default?

I'm not sure what you are talking about. What program and what applications?

> -hotkeys in what file?

If you mean shortcuts, all preferences are stored in ~/.config/xylosper/bomi/pref.json as JSON format including shortcuts and the key for shortcuts is 'shortcut_map' although I don't understand why you do need to know that.

**Comment by ForumLiker** [comment] 2015-03-18 10:23
look at these images
----
http://i57.fastpic.ru/big/2015/0318/ac/745e58958716c45cd16aa273b91c90ac.png
http://i57.fastpic.ru/big/2015/0318/25/73f420c4bb2002e0eb691e2696f15325.png

**Comment by xylosper** [comment] 2015-03-18 11:02
Frankly speaking, I don't even know what I'm looking at.
I don't understand neither of unity desktop settings and cyrillic alphabets.

**Comment by ForumLiker** [comment] 2015-03-18 11:06
open the System Settings window from the panel. Select the Details icon in the System Settings window.Select the Default Applications category. In "Video" no choice Bomi

**Comment by xylosper** [comment] 2015-03-18 12:06
What does `mimeopen --ask <a video file>` say?

**Comment by ForumLiker** [comment] 2015-03-18 13:29
@UBUNTU-PC:~/desktop$ mimeopen movie.avi --ask
Please choose a default application for files of type video/x-msvideo

	1) bomi  (bomi)
	2) Videos  (totem)
	3) Other...

use application #
but,in the context menu - to open in another program, no Bomi

**Comment by xylosper** [comment] 2015-03-19 05:45
Can you see other players in your list, for instance smplayer?

**Comment by ForumLiker** [comment] 2015-03-19 16:49
Yes, I see. Now install SMPlayer and he appeared in the list.

**Comment by xylosper** [comment] 2015-03-20 02:15
Please run `sudo update-desktop-database` and try again.

**Comment by ForumLiker** [comment] 2015-03-20 11:15
bomi has not appeared in the list

**Comment by xylosper** [comment] 2015-03-20 11:26
Well, I have no idea. I've tested in Ubuntu but I couldn't reproduce your problem.

**Comment by ForumLiker** [comment] 2015-03-25 18:16
I saved folder ~/.config/xylosper then reinstall ubuntu then returned the folder. 
my settings were not saved. Why???

**Comment by xylosper** [comment] 2015-03-25 18:37
What files are contained there?

**Comment by ForumLiker** [comment] 2015-03-26 08:47
"Xylosper">"bomi", bomi.conf
"bomi">appstate.json, history.db, history.db-shm, history.db-wal, objectstorage.ini, pref.json

**Comment by xylosper** [comment] 2015-03-26 08:49
> "Xylosper">"bomi", bomi.conf
Is 'X' capitalized?

**Comment by ForumLiker** [comment] 2015-03-26 08:50
I do not know. how to find out?

**Comment by xylosper** [comment] 2015-03-26 08:52
'X' is a capital letter. 'x' is a small letter. It should be small letter. That is, it should be xylosper not Xylosper.

**Comment by ForumLiker** [comment] 2015-03-26 08:53
"x" small letter

**Comment by xylosper** [comment] 2015-03-26 08:56
Then it should work. Are you sure you put them in right place?
Copy again and try
```
diff -bruN <pref.json in your backup> ~/.config/xylosper/bomi/pref.json
```
What's the result?

**Comment by ForumLiker** [comment] 2015-03-26 09:12
I have understood what was the problem. Folder "xylosper" has been saved in LiveCD. The problem was the Rights of folder)))

**Comment by xylosper** [comment] 2015-03-26 09:22
So, it solved? May I close this?

**Comment by ForumLiker** [comment] 2015-03-26 09:35
Ok. Thank you))

**Closed** 2015-03-26 09:37 UTC
